onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js
  - prisma
  - sharp
  - unrs-resolver

patchedDependencies:
  better-auth@1.3.4: patches/better-auth@1.3.4.patch
